### ISSUE TITLE
Adicionar sección de profesionais na JVM

### ISSUE THREAD

**Issue by antonmry** [vigojug/vigojug.github.io#18]
Unha especie de directorio onde o que queira pode añadirse para que as empresas a procura de traballo os contacten

**Comment by tomasalmeida** [comment]
Eso tendría sentido para freelancers y en paro, pero puede quedar vaciado porque en España es raro que una persona empleada que tenga interés en escuchar nuevas ofertas lo diga publicamente.

**Comment by antonmry** [comment]
Fechando, demasiado traballo, imos optar por algo máis sinxelo: https://github.com/vigojug/vigojug.github.io/issues/57
