### ISSUE TITLE
Web en master no es la equivalente en source

### ISSUE THREAD

**Issue by tomasalmeida** [vigojug/vigojug.github.io#19]
No comprendo porqué los commits en master desaparecieron y la web que está ahora no es la compilación de source. Sabes por qué?

**Comment by antonmry** [comment]
es un poco de lío... tenemos que meter en las PRs el contenido de output, así va a source, y de ahí a master publicado.

Inicialmente metí en el `.gitignore` el `output` y eso ha generado un montón de lío. Ahora ya debería estar. De todas formas, master es un branch de entrega, mejor utilizar `source` para hacer seguimiento de todo.

Échale un vistazo y si lo ves claro, cerramos esta issue, ok?

**Comment by tomasalmeida** [comment]
Perfecto, hoy hice la PR y fue todo bien. Cierro este!
