### ISSUE TITLE
Añadir pagina con todos los grupos "amigos" de Vigo

### ISSUE THREAD

**Issue by tomasalmeida** [vigojug/vigojug.github.io#23]
Añadir una sección con los otros grupos amigos en Vigo/Galicia.

**Comment by tomasalmeida** [comment]
@antonmry, te parece bien?

PS: voy a probar con este issue como funciona si antes de empezar a desarrollar algo, nos pedimos feedback.

**Comment by antonmry** [comment]
Sí, yo lo veo :+1: 

PD.: creo que algo están preparando los otros grupos en ese sentido, no sé todavía qué forma tendrá

**Comment by tomasalmeida** [comment]
Mi idea era simplemente poner una pagina con todos los grupos. Qué están pensando los otros?

**Comment by antonmry** [comment]
No lo sé, a ver si me entero mañana en el Vigolabs o el jueves en el PythonVigo :-)

**Comment by tomasalmeida** [comment]
en prod.
