### ISSUE TITLE
VigoJUG19: Programación de competición

### ISSUE THREAD

**Issue by antonmry** [vigojug/vigojug.github.io#68]
- [x] Confirmar temática e ponentes
- [x] Confirmar local: Kaleido
- [x] Cartel 
- [x] Crear en meetup
- [x] Confirmar calendar
- [x] Publicar en Slack
- [x] Publicar en Twitter, Linkedin. RT from VigoTech.
- [x] ~~Envío a universidades e FPs~~
- [x] ~~Envío a empresas~~
- [x] Mandar correo recordatorio (1 día antes)
- [x] ~~Preparar kahoot~~
- [x] Re anunciar en twitter e Slack (1 día antes)
- [x] Avisar o Porto Santo das cervezas
- [x] Avisar a Alex o tema das chaves
- [x] Facer o meetup
- [x] Subir slides a Meetup
- [x] Subir fotos a Meetup
- [x] Enviar la licencia al ganador
- [x] Lanzar o seguinte meetup

**Comment by antonmry** [comment]
@danybmx @mmmabbb alguno/a se podría encargar del tema de subir las fotos de Twitter a Meetup? Tenemos varias issues pendientes, es la típica cosa que siempre me da muchísima pereza :man_facepalming:

**Comment by danybmx** [comment]
@antonmry hecho lo de subir las fotos! https://www.meetup.com/VigoJUG/photos/29678395/

**Comment by antonmry** [comment]
gracias @danybmx, sería mucho abusar pedir hacerlo también en la #65 y la #66? y ya cerramos esas issues
