### ISSUE TITLE
Post: Proximas charlas

### ISSUE THREAD

**Issue by tomasalmeida** [vigojug/vigojug.github.io#7]
Sería este? https://github.com/vigojug/vigojug.github.io/pull/4

**Comment by antonmry** [comment]
Yep! Eu creo que sí. Podemos lanzar o novo post o día seguinte a cada charla (un mes de antelación parece unha boa cousa)

**Comment by tomasalmeida** [comment]
Perfecto, me parece bien. A cerrar este issue entonces 👍
