### ISSUE TITLE
VigoJUG 20: Containers In Anger with Micronaut

### ISSUE THREAD

**Issue by antonmry** [vigojug/vigojug.github.io#71]
- [x] Confirmar temática e ponentes: Antón
- [x] Confirmar local: Optare
- [x] Cartel 
- [x] Crear en meetup: https://www.meetup.com/VigoJUG/events/259527600/
- [x] Confirmar calendar
- [x] Publicar en Slack
- [x] Publicar en Twitter, Linkedin. RT from VigoTech.
- [x] ~~Envío a universidades e FPs~~
- [x] ~~Envío a empresas~~
- [x] Mandar correo recordatorio (1 día antes)
- [ ] Preparar kahoot
- [x] Re anunciar en twitter e Slack (1 día antes)
- [x] Cervexas / pizzas?
- [x] Avisar a Infra tema ladróns
- [x] Facer o meetup
- [x] Subir slides/código a Meetup
- [x] Subir fotos a Meetup
- [x] Enviar la licencia al ganador
- [x] Lanzar o seguinte meetup

**Comment by danybmx** [comment]
Se podría cerrar esta issue? @antonmry

**Comment by antonmry** [comment]
toda la razón :ok_hand:
