### ISSUE TITLE
VigoJUG21: CSS Grid

### ISSUE THREAD

**Issue by antonmry** [vigojug/vigojug.github.io#72]
- [x] Confirmar temática e ponentes: Daniil
- [x] Confirmar local: JukeBoxVigo
- [x] Cartel 
- [x] Crear en meetup: https://www.meetup.com/VigoJUG/events/260248209/
- [x] Confirmar calendar
- [ ] Publicar en Slack
- [ ] Publicar en Twitter, Linkedin. RT from VigoTech.
- [x] ~~Envío a universidades e FPs~~
- [x] ~~Envío a empresas~~
- [x] Mandar correo recordatorio (1 día antes)
- [x] Preparar kahoot
- [x] Re anunciar en twitter e Slack (1 día antes)
- [x] Cervexas / pizzas?
- [x] Facer o meetup
- [x] ~~Subir slides/código a Meetup~~
- [x] Subir fotos a Meetup
- [x] Enviar la licencia al ganador
- [x] Lanzar o seguinte meetup

**Comment by danybmx** [comment]
Se podría cerrar esta issue? @antonmry

**Comment by antonmry** [comment]
toda la razón :ok_hand:
