### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by tomasalmeida** [vigojug/vigojug.github.io#8]
Duda: eso no es el "quienes somos"?

**Comment by antonmry** [comment]
Estaba pensando en meter unha sección para enganchar con slack, redes sociais e tal cual. Qué te parece?

**Comment by tomasalmeida** [comment]
Perfecto! Un template nuevo con eso y añades otro link en el menu?

**Comment by antonmry** [comment]
Fasme dudar...template = page? Nas páxinas se pode meter html a piñon

**Comment by antonmry** [comment]
Fechando, demasiado traballo, imos optar por algo máis sinxelo: #57 e #58
